<?php


namespace App\Tests\Helpers\Traits;


trait ReposApiMockTrait
{
    /**
     * @return string
     */
    private function mockReposApiResponse(): string
    {
        return <<<EOT
    [
    {
        "id": 148280,
        "node_id": "MDEwOlJlcG9zaXRvcnkxNDgyODA=",
        "name": "roofparty",
        "full_name": "mxcl/roofparty",
        "private": false,
        "owner": {
            "login": "mxcl",
            "id": 58962,
            "node_id": "MDQ6VXNlcjU4OTYy",
            "avatar_url": "https://avatars.githubusercontent.com/u/58962?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/mxcl",
            "html_url": "https://github.com/mxcl",
            "followers_url": "https://api.github.com/users/mxcl/followers",
            "following_url": "https://api.github.com/users/mxcl/following{/other_user}",
            "gists_url": "https://api.github.com/users/mxcl/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/mxcl/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/mxcl/subscriptions",
            "organizations_url": "https://api.github.com/users/mxcl/orgs",
            "repos_url": "https://api.github.com/users/mxcl/repos",
            "events_url": "https://api.github.com/users/mxcl/events{/privacy}",
            "received_events_url": "https://api.github.com/users/mxcl/received_events",
            "type": "User",
            "site_admin": false
        },
        "html_url": "https://github.com/mxcl/roofparty",
        "description": "A Last.fm radio player written in D",
        "fork": false,
        "url": "https://api.github.com/repos/mxcl/roofparty",
        "forks_url": "https://api.github.com/repos/mxcl/roofparty/forks",
        "keys_url": "https://api.github.com/repos/mxcl/roofparty/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/mxcl/roofparty/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/mxcl/roofparty/teams",
        "hooks_url": "https://api.github.com/repos/mxcl/roofparty/hooks",
        "issue_events_url": "https://api.github.com/repos/mxcl/roofparty/issues/events{/number}",
        "events_url": "https://api.github.com/repos/mxcl/roofparty/events",
        "assignees_url": "https://api.github.com/repos/mxcl/roofparty/assignees{/user}",
        "branches_url": "https://api.github.com/repos/mxcl/roofparty/branches{/branch}",
        "tags_url": "https://api.github.com/repos/mxcl/roofparty/tags",
        "blobs_url": "https://api.github.com/repos/mxcl/roofparty/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/mxcl/roofparty/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/mxcl/roofparty/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/mxcl/roofparty/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/mxcl/roofparty/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/mxcl/roofparty/languages",
        "stargazers_url": "https://api.github.com/repos/mxcl/roofparty/stargazers",
        "contributors_url": "https://api.github.com/repos/mxcl/roofparty/contributors",
        "subscribers_url": "https://api.github.com/repos/mxcl/roofparty/subscribers",
        "subscription_url": "https://api.github.com/repos/mxcl/roofparty/subscription",
        "commits_url": "https://api.github.com/repos/mxcl/roofparty/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/mxcl/roofparty/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/mxcl/roofparty/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/mxcl/roofparty/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/mxcl/roofparty/contents/{+path}",
        "compare_url": "https://api.github.com/repos/mxcl/roofparty/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/mxcl/roofparty/merges",
        "archive_url": "https://api.github.com/repos/mxcl/roofparty/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/mxcl/roofparty/downloads",
        "issues_url": "https://api.github.com/repos/mxcl/roofparty/issues{/number}",
        "pulls_url": "https://api.github.com/repos/mxcl/roofparty/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/mxcl/roofparty/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/mxcl/roofparty/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/mxcl/roofparty/labels{/name}",
        "releases_url": "https://api.github.com/repos/mxcl/roofparty/releases{/id}",
        "deployments_url": "https://api.github.com/repos/mxcl/roofparty/deployments",
        "created_at": "2009-03-11T10:24:26Z",
        "updated_at": "2019-08-13T14:08:25Z",
        "pushed_at": "2009-03-11T10:27:45Z",
        "git_url": "git://github.com/mxcl/roofparty.git",
        "ssh_url": "git@github.com:mxcl/roofparty.git",
        "clone_url": "https://github.com/mxcl/roofparty.git",
        "svn_url": "https://github.com/mxcl/roofparty",
        "homepage": "",
        "size": 83,
        "stargazers_count": 5,
        "watchers_count": 5,
        "language": null,
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "forks_count": 1,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 0,
        "license": null,
        "forks": 1,
        "open_issues": 0,
        "watchers": 5,
        "default_branch": "master"
    },
    {
        "id": 155855,
        "node_id": "MDEwOlJlcG9zaXRvcnkxNTU4NTU=",
        "name": "playdar.prefpane",
        "full_name": "mxcl/playdar.prefpane",
        "private": false,
        "owner": {
            "login": "mxcl",
            "id": 58962,
            "node_id": "MDQ6VXNlcjU4OTYy",
            "avatar_url": "https://avatars.githubusercontent.com/u/58962?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/mxcl",
            "html_url": "https://github.com/mxcl",
            "followers_url": "https://api.github.com/users/mxcl/followers",
            "following_url": "https://api.github.com/users/mxcl/following{/other_user}",
            "gists_url": "https://api.github.com/users/mxcl/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/mxcl/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/mxcl/subscriptions",
            "organizations_url": "https://api.github.com/users/mxcl/orgs",
            "repos_url": "https://api.github.com/users/mxcl/repos",
            "events_url": "https://api.github.com/users/mxcl/events{/privacy}",
            "received_events_url": "https://api.github.com/users/mxcl/received_events",
            "type": "User",
            "site_admin": false
        },
        "html_url": "https://github.com/mxcl/playdar.prefpane",
        "description": "All in one Mac OS X Preference Pane for the Playdar daemon",
        "fork": false,
        "url": "https://api.github.com/repos/mxcl/playdar.prefpane",
        "forks_url": "https://api.github.com/repos/mxcl/playdar.prefpane/forks",
        "keys_url": "https://api.github.com/repos/mxcl/playdar.prefpane/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/mxcl/playdar.prefpane/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/mxcl/playdar.prefpane/teams",
        "hooks_url": "https://api.github.com/repos/mxcl/playdar.prefpane/hooks",
        "issue_events_url": "https://api.github.com/repos/mxcl/playdar.prefpane/issues/events{/number}",
        "events_url": "https://api.github.com/repos/mxcl/playdar.prefpane/events",
        "assignees_url": "https://api.github.com/repos/mxcl/playdar.prefpane/assignees{/user}",
        "branches_url": "https://api.github.com/repos/mxcl/playdar.prefpane/branches{/branch}",
        "tags_url": "https://api.github.com/repos/mxcl/playdar.prefpane/tags",
        "blobs_url": "https://api.github.com/repos/mxcl/playdar.prefpane/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/mxcl/playdar.prefpane/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/mxcl/playdar.prefpane/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/mxcl/playdar.prefpane/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/mxcl/playdar.prefpane/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/mxcl/playdar.prefpane/languages",
        "stargazers_url": "https://api.github.com/repos/mxcl/playdar.prefpane/stargazers",
        "contributors_url": "https://api.github.com/repos/mxcl/playdar.prefpane/contributors",
        "subscribers_url": "https://api.github.com/repos/mxcl/playdar.prefpane/subscribers",
        "subscription_url": "https://api.github.com/repos/mxcl/playdar.prefpane/subscription",
        "commits_url": "https://api.github.com/repos/mxcl/playdar.prefpane/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/mxcl/playdar.prefpane/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/mxcl/playdar.prefpane/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/mxcl/playdar.prefpane/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/mxcl/playdar.prefpane/contents/{+path}",
        "compare_url": "https://api.github.com/repos/mxcl/playdar.prefpane/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/mxcl/playdar.prefpane/merges",
        "archive_url": "https://api.github.com/repos/mxcl/playdar.prefpane/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/mxcl/playdar.prefpane/downloads",
        "issues_url": "https://api.github.com/repos/mxcl/playdar.prefpane/issues{/number}",
        "pulls_url": "https://api.github.com/repos/mxcl/playdar.prefpane/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/mxcl/playdar.prefpane/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/mxcl/playdar.prefpane/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/mxcl/playdar.prefpane/labels{/name}",
        "releases_url": "https://api.github.com/repos/mxcl/playdar.prefpane/releases{/id}",
        "deployments_url": "https://api.github.com/repos/mxcl/playdar.prefpane/deployments",
        "created_at": "2009-03-21T17:23:47Z",
        "updated_at": "2020-11-13T14:40:15Z",
        "pushed_at": "2009-12-07T15:21:19Z",
        "git_url": "git://github.com/mxcl/playdar.prefpane.git",
        "ssh_url": "git@github.com:mxcl/playdar.prefpane.git",
        "clone_url": "https://github.com/mxcl/playdar.prefpane.git",
        "svn_url": "https://github.com/mxcl/playdar.prefpane",
        "homepage": "http://www.methylblue.com/playdar/",
        "size": 1039,
        "stargazers_count": 26,
        "watchers_count": 26,
        "language": "Objective-C",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "forks_count": 1,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 3,
        "license": {
            "key": "gpl-3.0",
            "name": "GNU General Public License v3.0",
            "spdx_id": "GPL-3.0",
            "url": "https://api.github.com/licenses/gpl-3.0",
            "node_id": "MDc6TGljZW5zZTk="
        },
        "forks": 1,
        "open_issues": 3,
        "watchers": 26,
        "default_branch": "master"
    },
    {
        "id": 223054,
        "node_id": "MDEwOlJlcG9zaXRvcnkyMjMwNTQ=",
        "name": "scrobsub",
        "full_name": "mxcl/scrobsub",
        "private": false,
        "owner": {
            "login": "mxcl",
            "id": 58962,
            "node_id": "MDQ6VXNlcjU4OTYy",
            "avatar_url": "https://avatars.githubusercontent.com/u/58962?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/mxcl",
            "html_url": "https://github.com/mxcl",
            "followers_url": "https://api.github.com/users/mxcl/followers",
            "following_url": "https://api.github.com/users/mxcl/following{/other_user}",
            "gists_url": "https://api.github.com/users/mxcl/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/mxcl/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/mxcl/subscriptions",
            "organizations_url": "https://api.github.com/users/mxcl/orgs",
            "repos_url": "https://api.github.com/users/mxcl/repos",
            "events_url": "https://api.github.com/users/mxcl/events{/privacy}",
            "received_events_url": "https://api.github.com/users/mxcl/received_events",
            "type": "User",
            "site_admin": false
        },
        "html_url": "https://github.com/mxcl/scrobsub",
        "description": "Portable scrobbling solution in plain c",
        "fork": false,
        "url": "https://api.github.com/repos/mxcl/scrobsub",
        "forks_url": "https://api.github.com/repos/mxcl/scrobsub/forks",
        "keys_url": "https://api.github.com/repos/mxcl/scrobsub/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/mxcl/scrobsub/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/mxcl/scrobsub/teams",
        "hooks_url": "https://api.github.com/repos/mxcl/scrobsub/hooks",
        "issue_events_url": "https://api.github.com/repos/mxcl/scrobsub/issues/events{/number}",
        "events_url": "https://api.github.com/repos/mxcl/scrobsub/events",
        "assignees_url": "https://api.github.com/repos/mxcl/scrobsub/assignees{/user}",
        "branches_url": "https://api.github.com/repos/mxcl/scrobsub/branches{/branch}",
        "tags_url": "https://api.github.com/repos/mxcl/scrobsub/tags",
        "blobs_url": "https://api.github.com/repos/mxcl/scrobsub/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/mxcl/scrobsub/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/mxcl/scrobsub/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/mxcl/scrobsub/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/mxcl/scrobsub/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/mxcl/scrobsub/languages",
        "stargazers_url": "https://api.github.com/repos/mxcl/scrobsub/stargazers",
        "contributors_url": "https://api.github.com/repos/mxcl/scrobsub/contributors",
        "subscribers_url": "https://api.github.com/repos/mxcl/scrobsub/subscribers",
        "subscription_url": "https://api.github.com/repos/mxcl/scrobsub/subscription",
        "commits_url": "https://api.github.com/repos/mxcl/scrobsub/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/mxcl/scrobsub/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/mxcl/scrobsub/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/mxcl/scrobsub/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/mxcl/scrobsub/contents/{+path}",
        "compare_url": "https://api.github.com/repos/mxcl/scrobsub/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/mxcl/scrobsub/merges",
        "archive_url": "https://api.github.com/repos/mxcl/scrobsub/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/mxcl/scrobsub/downloads",
        "issues_url": "https://api.github.com/repos/mxcl/scrobsub/issues{/number}",
        "pulls_url": "https://api.github.com/repos/mxcl/scrobsub/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/mxcl/scrobsub/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/mxcl/scrobsub/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/mxcl/scrobsub/labels{/name}",
        "releases_url": "https://api.github.com/repos/mxcl/scrobsub/releases{/id}",
        "deployments_url": "https://api.github.com/repos/mxcl/scrobsub/deployments",
        "created_at": "2009-06-09T22:43:00Z",
        "updated_at": "2020-05-03T09:02:33Z",
        "pushed_at": "2009-07-17T20:04:22Z",
        "git_url": "git://github.com/mxcl/scrobsub.git",
        "ssh_url": "git@github.com:mxcl/scrobsub.git",
        "clone_url": "https://github.com/mxcl/scrobsub.git",
        "svn_url": "https://github.com/mxcl/scrobsub",
        "homepage": "",
        "size": 123,
        "stargazers_count": 9,
        "watchers_count": 9,
        "language": "C",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "forks_count": 2,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 0,
        "license": null,
        "forks": 2,
        "open_issues": 0,
        "watchers": 9,
        "default_branch": "master"
    }
]
EOT;
    }

    public function mockReposApiErrorResponse(): string
    {
        return '{
          "message": "Not Found",
          "documentation_url": "https://docs.github.com/rest/reference/repos#list-repositories-for-a-user"
        }';
    }
}
